# Generated by Django 5.1.4 on 2024-12-12 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del archivo', max_length=100)),
                ('url', models.URLField(help_text='URL del archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del usuario', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Perfil de LinkedIn', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('tipo_usuario', models.CharField(choices=[('empresa', 'Empresa'), ('candidato', 'Candidato')], help_text='Tipo de usuario', max_length=20)),
                ('portafolio_url', models.URLField(blank=True, help_text='URL del portafolio del candidato', null=True)),
                ('nivel_estudios', models.JSONField(help_text='Niveles de estudio del candidato')),
                ('habilidades_tecnicas', models.JSONField(help_text='Habilidades técnicas')),
                ('habilidades_blandas', models.JSONField(help_text='Habilidades blandas')),
                ('idiomas', models.JSONField(help_text='Idiomas conocidos')),
                ('experiencia_laboral', models.JSONField(help_text='Experiencia laboral')),
                ('cursos_certificados', models.JSONField(blank=True, help_text='Cursos certificados del candidato', null=True)),
                ('grado_discapacidad', models.IntegerField(help_text='Grado de discapacidad')),
                ('discapacidades', models.JSONField(blank=True, help_text='Detalles de discapacidades', null=True)),
                ('user', models.OneToOneField(help_text='Usuario al que pertenece este candidato', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Comentario')),
                ('puntuacion', models.IntegerField(help_text='Puntuación del comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha del comentario')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioInclusión',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del criterio', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción del criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del usuario', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Perfil de LinkedIn', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('tipo_usuario', models.CharField(choices=[('empresa', 'Empresa'), ('candidato', 'Candidato')], help_text='Tipo de usuario', max_length=20)),
                ('nombre_empresa', models.CharField(help_text='Nombre de la empresa', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la empresa', null=True)),
                ('ubicacion', models.CharField(help_text='Ubicación de la empresa', max_length=100)),
                ('puntuacion_promedio', models.FloatField(default=0.0, help_text='Puntuación promedio basada en comentarios')),
                ('user', models.OneToOneField(help_text='Usuario al que pertenece esta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaDeEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la oferta', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de la oferta')),
                ('requisitos', models.JSONField(help_text='Requisitos de la oferta')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de publicación')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', help_text='Estado de la oferta', max_length=20)),
                ('empresa', models.ForeignKey(help_text='Empresa que publica la oferta', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='empleos.empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='empleos.empresa'),
        ),
    ]
