# Generated by Django 5.1.4 on 2024-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_archivo_candidato_comentario_criterioinclusión_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterioinclusión',
            options={'verbose_name': 'Criterio de inclusión', 'verbose_name_plural': 'Criterios de inclusión'},
        ),
        migrations.AlterModelOptions(
            name='ofertadeempleo',
            options={'verbose_name': 'Oferta de empleo', 'verbose_name_plural': 'Ofertas de empleo'},
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nivel_estudios',
            field=models.CharField(choices=[('bachiller', 'Bachiller'), ('tercer_nivel', 'Título de tercer nivel'), ('maestria', 'Maestría o especialidad'), ('doctorado', 'Doctorado'), ('postdoctorado', 'Postdoctorado')], help_text='Nivel de estudios del candidato', max_length=20),
        ),
    ]
