# Generated by Django 5.1.4 on 2024-12-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_alter_criterioinclusión_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='grado_discapacidad',
            field=models.CharField(choices=[('ninguna', 'Ninguna discapacidad (del 0% y 4%)'), ('leve', 'Leve (del 5% y 24%)'), ('moderada', 'Moderada (del 25% al 49%)'), ('grave', 'Grave (del 50% al 74%)'), ('muy_grave', 'Muy grave (del 75 % al 95 %)'), ('completa', 'Completa (el 100 %)')], default='ninguna', help_text='Grado de discapacidad del candidato', max_length=20),
        ),
    ]
