# Generated by Django 5.1.4 on 2024-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_alter_candidato_grado_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='tipo_usuario',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('candidato', 'Candidato')], default='candidato', help_text='Tipo de usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_usuario',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('candidato', 'Candidato')], default='candidato', help_text='Tipo de usuario', max_length=20),
        ),
    ]
