# Generated by Django 5.1.4 on 2024-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_alter_candidato_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuario/foto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuario/foto'),
        ),
    ]
