# Generated by Django 5.1.4 on 2024-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0007_alter_candidato_experiencia_laboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adecuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la adecuación', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción de la adecuación')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='adecuaciones',
            field=models.ManyToManyField(blank=True, help_text='Adecuaciones disponibles en la empresa', to='empleos.adecuacion'),
        ),
    ]
