# Generated by Django 5.1.4 on 2024-12-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0008_adecuacion_empresa_adecuaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadeempleo',
            name='criterios_inclusion',
            field=models.ManyToManyField(blank=True, help_text='Criterios de inclusión para la oferta', to='empleos.criterioinclusión'),
        ),
    ]
