# Generated by Django 5.1.4 on 2025-01-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0009_ofertadeempleo_criterios_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='descripcion_personal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='documentos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='instituciones_educativas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
