# Generated by Django 5.1.4 on 2025-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0010_candidato_descripcion_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='discapacidades',
            field=models.CharField(blank=True, help_text='Detalles de discapacidades', max_length=25, null=True),
        ),
    ]
