# Generated by Django 5.1.4 on 2025-01-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0011_alter_candidato_discapacidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='descripcion_personal',
            new_name='descripcion_personales',
        ),
    ]
