# Generated by Django 5.1.4 on 2025-01-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0012_rename_descripcion_personal_candidato_descripcion_personales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='descripcion_personales',
            new_name='descripcion_personal',
        ),
    ]
