# Generated by Django 5.1.4 on 2025-01-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0014_ofertadeempleo_preguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(blank=True, help_text='Respuestas del candidato a las preguntas', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha de la solicitud')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='empleos.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='empleos.ofertadeempleo')),
            ],
        ),
    ]
