# Generated by Django 5.1.4 on 2025-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0015_solicituddeempleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeempleo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('aceptada', 'Aceptada')], default='pendiente', help_text='Estado de la solicitud', max_length=20),
        ),
    ]
