# Generated by Django 5.1.4 on 2025-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0016_solicituddeempleo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeempleo',
            name='calificada',
            field=models.BooleanField(default=False, help_text='Indica si la experiencia ya fue calificada'),
        ),
    ]
