# Generated by Django 5.1.4 on 2025-01-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0017_solicituddeempleo_calificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeempleo',
            name='analisis_de_ia',
            field=models.TextField(blank=True, help_text='Análisis generado por IA', null=True),
        ),
    ]
